### PR TITLE
Refactor kit

### PR DESCRIPTION
**Pull request by ZakAyesh**
The purpose of this PR is to refactor this kit to improve the Readme and remove Foundry (meaning Hardhat will be used as the main development environment).

### CODE REVIEW

**Comment by aashidham** [comment]
Looks like a great start! 

To remove forge altogether though, shouldn't you also adjust the README and / or tooling here: https://github.com/filecoin-project/fvm-starter-kit-deal-making/tree/main/client-contract?

Ideally the readme and / or tooling in this repo should also be adjusted so that it is clear to the dev to deploy the client contract through hardhat. 

Remember, as the client contract evolves, the latest source of truth will be in this repo. It might be confusing journey for the dev if they see one version of the contract on this repo (with forge instructions), and another on the hardhat repo (with hardhat instructions). 

I see a couple of options here:
1. Remove the build tooling (Makefile, etc) in the client-contract directory and replace with hardhat tooling
2. Keep the forge build tooling in this directory, but then clarify with the README inside the client-contract directory that there is also hardhat tooling to deploy this contract on your repo.

I would prefer 1, since it seems cleanest. Up to you though.

**Comment by honghaoq** [comment]
Thanks! Should we add pointer on how to get datacap (via glif autoverifier) to start with?

**Comment by ZakAyesh** [comment]
> To remove forge altogether though, shouldn't you also adjust the README and / or tooling here: https://github.com/filecoin-project/fvm-starter-kit-deal-making/tree/main/client-contract?

@aashidham The reason I left that there, is because this repo has coupled purposes. It is a source of truth for the devs to build on and be referenced. It is also a demo kit for devs to experiment with the client contract. That folder is where devs develop the core contract itself and is owned by the engineers, correct? 

If this was purely a demo kit, I would just totally remove that Readme. However, many of the engineers working on the development of the client contract prefer Foundry, so I would hesitate to remove it without their approval.

**Comment by ZakAyesh** [comment]
@honghaoq agreed. I had that in there originally, but it started to make the Readme too lengthy and confusing (that's a lot of topics to introduce). I'll try to fit in a reference to Filplus docs somewhere it makes sense.

**Comment by raulk** [comment]
@aashidham looks like this is ready?

**Comment by raulk** [comment]
Went through the history and noted that the last commit led to the -16k LOC diff as Foundry was removed. Checking further.

**Comment by raulk** [comment]
Doesn't this PR leave us in an end state where hardhat kit linked as a submodule here is _not_ actually deploying the contract in this repo, but rather the client contract embedded in the hardhat kit itself? That isn't what we want.

1. This repo is the source of truth for the client contract.
2. If fevm-hardhat-kit offers a client contract demo, it must reference this repo.
3. If fevm-hardhat-kit does NOT offer a client demo, there should be a demo here.

**Pull request merged**
